[
  "#include <Wire.h>",
  "#include <LiquidCrystal_I2C.h>",
  "#include <DHT.h>",
  "#include <Servo.h>",
  "",
  "#define LDR_PIN A0",
  "#define DHT_PIN 4",
  "#define PIR_PIN 5",
  "#define SERVO_PIN 6",
  "#define TRIG_PIN 7",
  "#define ECHO_PIN 8",
  "",
  "// Initialize the libraries",
  "LiquidCrystal_I2C lcd(0x27, 16, 2); // Set the LCD address (0x27), 16 columns and 2 rows",
  "DHT dht(DHT_PIN, DHT22); // Initialize the DHT sensor",
  "Servo myServo;",
  "",
  "// Variables for motion detection",
  "int pirState = LOW;",
  "long duration, distance;",
  "",
  "void setup() {",
  "  // Initialize Serial",
  "  Serial.begin(9600);",
  "  ",
  "  // Initialize LCD",
  "  lcd.begin();",
  "  lcd.backlight();",
  "  ",
  "  // Initialize DHT sensor",
  "  dht.begin();",
  "  ",
  "  // Initialize Servo",
  "  myServo.attach(SERVO_PIN);",
  "",
  "  // Setup PIR sensor",
  "  pinMode(PIR_PIN, INPUT);",
  "  ",
  "  // Setup Ultrasonic sensor",
  "  pinMode(TRIG_PIN, OUTPUT);",
  "  pinMode(ECHO_PIN, INPUT);",
  "}",
  "",
  "void loop() {",
  "  // Read humidity and temperature",
  "  float humidity = dht.readHumidity();",
  "  float temperature = dht.readTemperature();",
  "",
  "  // Get LDR value",
  "  int ldrValue = analogRead(LDR_PIN);",
  "",
  "  // Check if there is motion detected",
  "  pirState = digitalRead(PIR_PIN);",
  "  ",
  "  if (pirState == HIGH) {",
  "    // Activate servo to trigger alarm",
  "    myServo.write(90); // Move servo to 90 degrees",
  "    lcd.clear();",
  "    lcd.print(\"Motion Detected!\");",
  "  } else {",
  "    myServo.write(0); // Reset servo",
  "    lcd.clear();",
  "    lcd.print(\"All Quiet\");",
  "  }",
  "",
  "  // Calculate distance using Ultrasonic sensor",
  "  digitalWrite(TRIG_PIN, LOW);",
  "  delayMicroseconds(2);",
  "  digitalWrite(TRIG_PIN, HIGH);",
  "  delayMicroseconds(10);",
  "  digitalWrite(TRIG_PIN, LOW);",
  "  duration = pulseIn(ECHO_PIN, HIGH);",
  "  distance = (duration * 0.034) / 2; // Calculate distance",
  "",
  "  // Display on LCD",
  "  lcd.setCursor(0, 1); // Move cursor to the second row",
  "  lcd.print(\"Temp: \");",
  "  lcd.print(temperature);",
  "  lcd.print(\"C LDR: \");",
  "  lcd.print(ldrValue);",
  "  ",
  "  delay(2000); // Wait for 2 seconds before the next loop",
  "}"
]